### ISSUE TITLE
Not able to import `colormaps` from matplotlib

### ISSUE THREAD

**Issue by mukesh-kumar-singh** [vijayvarma392/gw_eccentricity#188]
I tried installing `gw_eccentricity` in one `igwn-py39` enviornment and `import gw_eccentricity` gives me the following error:
```
File ~/.local/lib/python3.9/site-packages/gw_eccentricity/plot_settings.py:4, in <module>
      2 from matplotlib import rc
      3 from cycler import cycler
----> 4 from matplotlib import colormaps
      6 dark2 = colormaps["Dark2"].colors
      8 colorsDict = {
      9     "default": dark2[1],  # brown
     10     "apocenter": dark2[3],  # dark2[2],  # purple
   (...)
     29     "blue": "tab:blue"
     30 }

ImportError: cannot import name 'colormaps' from 'matplotlib' (/home1/mukesh.singh/miniconda3/envs/igwn-py39/lib/python3.9/site-packages/matplotlib/__init__.py)
```
which essentially means that there is no `colormaps` object in `matplotlib`. Do you think it's some version issue?

**Comment by duetosymmetry** [comment]
What version of matplotlib do you have? I think before matplotlib 3.5.0, the way to do this was `from matplotlib.cm import _colormaps as colormaps`. Starting with 3.5.0, you can do `from matplotlib import colormaps`.

**Comment by mukesh-kumar-singh** [comment]
I am using matplotlib version: `3.4.3`. Ok then it seems the import statements has to be changed for the older versions. Thanks!

**Comment by md-arif-shaikh** [comment]
Added a `matplotlib` version check and import colormaps accordingly #190
