### ISSUE TITLE
get_orbit_averaged_omega22_at_peri/apocenters are poorly named?

### ISSUE THREAD

**Issue by vijayvarma392** [vijayvarma392/gw_eccentricity#189]
Looking at the description
https://github.com/vijayvarma392/gw_eccentricity/blob/6954b10b8fb2519aee860e686d588c1599b26b7c/gw_eccentricity/eccDefinition.py#L1531
and Eqs.12-13 of the paper https://arxiv.org/pdf/2302.11257.pdf,
a more appropriate name might be `get_orbit_averaged_omega22_between_peri/apocenters`?

This recently tripped up PJ:
<img width="936" alt="image" src="https://github.com/vijayvarma392/gw_eccentricity/assets/9355891/064acdb8-6ad7-4d1c-8f24-001bac8c3ba8">

**Comment by PunJustice** [comment]
@haraldp271 this is what we discussed earlier today.

**Comment by haraldp271** [comment]
Agreed.  But looking at the documentation in the source code, what would also have helped is a more concise explanation in the help text of *what the function returns*. The important point is to keep this short and concise, so not to be lost in too much text/details.  Specifically I recommend that the help text begins with something like this:

'''
Given 'N' periastron points at times t_i, i=0...N-1, this function returns a np.array of length N-1, where result[i] is the frequency averaged over [t_i, t_{i+1}].  
'''

**Comment by md-arif-shaikh** [comment]
addressed by #191
