### ISSUE TITLE
Actions broken

### ISSUE THREAD

**Issue by vijayvarma392** [vijayvarma392/gw_eccentricity#213]
You should be able to fix it like this https://github.com/vijayvarma392/surfinBH/commit/fbff946117cc42d7dc55126b94ce710da174095b

**Comment by vijayvarma392** [comment]
any luck with this?

**Comment by md-arif-shaikh** [comment]
Failing due to some issue while building `spinsfast` package
![image](https://github.com/vijayvarma392/gw_eccentricity/assets/44096766/f23d151c-cf1d-4089-9ecf-373f6922b86b)

**Comment by md-arif-shaikh** [comment]
maybe of changes made in spinsfast last week?
![image](https://github.com/vijayvarma392/gw_eccentricity/assets/44096766/a2b88861-77c9-4192-844f-9bb03ac58a3f)

**Comment by md-arif-shaikh** [comment]
can we temporarily remove `sxs` from dependency? The tests do not use `sxs`. `spinsfast` is required by `sxs`, so removing `sxs` may be a temporary fix. @vijayvarma392

**Comment by vijayvarma392** [comment]
The real error might be something else:
<img width="1265" alt="image" src="https://github.com/vijayvarma392/gw_eccentricity/assets/9355891/50859a69-038c-4cdd-8855-9be88c48b335">

Is sxs an actual dependency for the package? If so, we shouldn't just remove it. 

Looks like only the macos test was run though: https://github.com/vijayvarma392/gw_eccentricity/actions/runs/8890734138/job/25533440833?pr=214. Can you try disabling macos test so that the ubuntu test is forced to run?

**Comment by vijayvarma392** [comment]
Also, maybe worth trying newer python versions: https://github.com/moble/spinsfast/blob/main/.github/workflows/build.yml#L18

**Comment by md-arif-shaikh** [comment]
Should this be closed now @vijayvarma392?

**Comment by vijayvarma392** [comment]
Yes, and feel free to take executive decisions about which issues can be closed :)
