### ISSUE TITLE
Implement instantaneous PN eccentricity calculations from waveform charges (or fluxes if charges not available)

### ISSUE THREAD

**Issue by duetosymmetry** [vijayvarma392/gw_eccentricity#22]
See e.g. the 3PN eccentricities in equations (20b),  (20d), and (20r) in [gr-qc/0407049](https://arxiv.org/abs/gr-qc/0407049), screen grabs below. Here E is the energy, h=J/(GM) is the scaled angular momentum, and eta is the reduced mass ratio. We would get E(t) and J(t) from the waveforms themselves. If we have asymptotic Bondi data (for CCE waveforms), we can compute the energy and angular momentum charges using [scri.asymptotic_bondi_data.bms_charges](https://scri.readthedocs.io/en/latest/_autosummary/scri.asymptotic_bondi_data.bms_charges.html). However if we only have strain, we can fake it by computing energy flux and angular momentum flux with [scri.WaveformModes.{energy,angular_momentum}_flux](https://scri.readthedocs.io/en/latest/_autosummary/scri.waveform_modes.html#scri.waveform_modes.WaveformModes.energy_flux), and integrating. Not 100% sure how to fix the two integration constants at early times. In [1802.04276](https://arxiv.org/abs/1802.04276) Eq. (3) we used a quasicircular post-Newtonian expression for \dot{E} as a function of E to fix the integration constant. Perhaps one can solve for (E,J) from \dot{E} and \dot{J} using leading PN (e.g. Peters and Mathews 1964), except this requires knowing the initial eccentricity!

![image](https://user-images.githubusercontent.com/679461/164489589-ece17679-c385-4f23-87d4-3a61ad294e10.png)
![image](https://user-images.githubusercontent.com/679461/164489692-ca2c066a-24ff-448c-9a19-103d95d2b5bb.png)
![image](https://user-images.githubusercontent.com/679461/164489769-2679c477-a4ee-4ff8-aa79-3a8f4948991e.png)

**Comment by vijayvarma392** [comment]
@duetosymmetry, to address a referee comment, we are adding a brief discussion on this approach in our paper. @MvdMeent added the stuff in red here:
<img width="563" alt="image" src="https://user-images.githubusercontent.com/9355891/235681225-8e384804-ce02-4f83-9afc-3edf24773baf.png">
<img width="556" alt="image" src="https://user-images.githubusercontent.com/9355891/235681272-119769f5-6b92-4820-ae0d-637cee3925cc.png">

This is essentially saying that this approach won't really work.
Wanted to also get your thoughts...are we missing something?

**Comment by duetosymmetry** [comment]
First, a slight technical point: even if \ell>1 supertranslations are fixed, E and J (or their fluxes) would still be Poincare-covariant, not invariant. Allowing supertranslations, the Bondi angular momentum is supertranslation-covariant, too (except maybe for the Chen-Wang-Yau angular momentum, which I haven't studied yet, but @keefemitman has).

I don't understand the argument for why this approach can't work. "Perfect knowledge of the (E,J)-track — which is not available" doesn't seem like a very precise argument for why it can't work. It can be found up to some PN order, based on how much PN the community can stand to slog through. It's true that this approach won't work after PN breaks down unless there is some other way to figure out (E,J) as a function of reference binary parameters. Maybe the breakdown of PN and not knowing something to use after that point is a more precise version of the argument.

Actually I think I started writing before remembering the full context... to do things based on (E,J), we would need to have the whole 2-sphere's worth of waveforms on scri (or at least up to some ell mode, say 4). If we just have a "measured" waveform at one point on scri, then we can't do the integrals to compute (E,J).

Even if we do have many ell modes on scri, there is a practical problem. If somebody gives you a bunch of modes without telling you the BMS frame or the system parameters, you could only start to use (E,J) to figure out eccentricity if you first fix the BMS frame to, say, the PN definition; and also need to optimize to find the system parameters. In which case I think this boils down to just fitting the early inspiral portion to PN waveforms, like what Dongze is doing. In which case this approach would fail the criterion of "computation should be cheap and robust".

**Comment by MvdMeent** [comment]
The problem with having imperfect knowledge if the e=0 EJ-track, is that you might be presented with with values of EJ that are not are not reachable is, say the 3PN conservative dynamics. This would lead to assigning a negative value to e^2, and therefore an imaginary value to e. Even with perfect knowledge of the e=0 line, an imperfect waveform model may still wander into the forbidden region and cause the same problem.

**Comment by duetosymmetry** [comment]
Ok, sounds like you're also saying the issue would be a breakdown of PN. Thanks for clarifying what you meant!

In retrospect I think the issues I raised afterwards are more problematic: if you only having a measurement at a point of scri, you don't have (E,J); or needing to simultaneously fit PN params and BMS frame params which boils down to essentially doing full parameter estimation w/ PN waveforms and thus very slow.

**Comment by MvdMeent** [comment]
Note, our current definition also doesn't work if you only have a single point at scri, since it is based off the 22-mode of the waveform. We are thus already taking some fixed frame at scri for granted.

"Breakdown of PN" makes it sound like this would only be a problem in the strong field, but (depending on the sign of the higher PN terms) the assignment of negative e^2 could persist all the way to the Newtonian limit. In any case, with only approximate knowledge of the e=0 line, we would always loose the ability to meaningfully assign small eccentricities.

I agree that the practicalities of actually obtaining E and J are at least as important a reason not to go down this route. My objection however, applies equally to other approaches that work by inverting as set of conservative "constants of motion" (e.g. the orbit averaged frequencies) that do not naturally vanish in the QC limit.

**Comment by md-arif-shaikh** [comment]
This has been now also discussed in Sec. II.B of  [arXiv:2302.11257](https://arxiv.org/pdf/2302.11257.pdf). Should this be closed now? @vijayvarma392

**Comment by md-arif-shaikh** [comment]
Closing this as this approach does not fully satisfy our criteria for defining eccentricity and the relevant arguments are there in this thread as well as in the paper.
