### ISSUE TITLE
Should we switch to always using phenomT for the zeroecc waveform?

### ISSUE THREAD

**Issue by vijayvarma392** [vijayvarma392/gw_eccentricity#81]
Right now, we use PhenomT only for NR, while for other models like SEOB/TEOBResum we use the quasicircular limit of those models.
Another option is we say our _definition_ of ecc/meanano is to use PhenomT as the quasicircular waveform. This can make it more standard in some sense.
However, for the package itself, the user is required to provide the dataDict, so it's up to them.
I'm talking more about what plots we show in the paper.

**Comment by md-arif-shaikh** [comment]
We already have the option to provide the approximant for zero ecc waveform when loading NR modes. For LAL it uses the same approximant as the ecc one. May be add an option for LAL as well in the future. Closing it for now.
