### ISSUE TITLE
How should we handle failures?

### ISSUE THREAD

**Issue by vijayvarma392** [vijayvarma392/gw_eccentricity#84]
What should the code do when it cannot measure ecc?
For example, for the Amp method when we are at small ecc and very close to the merger.
When tref_in has a bunch of times/freqs, it just returns those times/freqs where it can measure ecc, but think of the PE scenario where the user has one time/freq and sometimes that happens to not work.

How about the following behavior: 
By default, it raises an error.
But if an option like "failures_are_set_to_zero" = True, the method then sets ecc=mean_ano=0.
There should be a big warning in the docs about using this.

But, at least for the Amp method, we expect failures only when ecc is really small, so this might be good enough at current sensitivities. I mean, who cares about the difference between ecc=1e-5 and 1e-3?

One would have to be more careful for FrequencyFits, of course, at least until we are happy with its robustness.

**Comment by md-arif-shaikh** [comment]
Moving this to #206
