### ISSUE TITLE
Also check priors when doing PE tests

### ISSUE THREAD

**Issue by vijayvarma392** [vijayvarma392/gw_eccentricity#89]
A good point raised by @AntoniRamosBuades today:
When looking at PE results, it's also important to check what happens to the priors.
This would need: finding out what priors were used in the original analysis.
Draw samples from the prior, and repeat exactly what you do for the posterior samples: generate waveforms, compute ecc/mean_ano. Then compare the priors on the measured ecc/mean_ano with the priors on the model's ecc/mean_ano.
We may even want to reweight the posteriors so that the effective prior in the measured params are flat.

**Comment by md-arif-shaikh** [comment]
Something to keep in mind when converting posterior to standard definition but no longer need it to be open.
